name: Status
main: Status\Status
version: "1.0"
author: TeleMC
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0
- 3.1.0
- 4.0.0
commands:
  스탯관리:
    decription: 스탯
